# CodeRabbit configuration
# https://docs.coderabbit.ai/reference/configuration-template
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ja-JP

reviews:
  auto_apply_labels: true
  poem: true
  finishing_touches:
    unit_tests:
      enabled: false
  tools:
    presidio:
      enabled: false

code_generation:
  docstrings:
    language: ja-JP

issue_enrichment:
  auto_enrich:
    enabled: true
  labeling:
    auto_apply_labels: true
